### ISSUE TITLE
Exception with PlatformViews when using FlutterFragmentActivity

### ISSUE THREAD

**Issue by deepak786** [deepak786/intercom_flutter#273]
Starting with Intercom v14 (`intercom_flutter: 7.6.0`), MainActivity has to extend FlutterFragmentActivity instead of FlutterActivity.
But using the FlutterFragmentActivity, there is an exception with PlatformViews. See https://github.com/v3rm0n/intercom_flutter/issues/270#issuecomment-1331014605

**Comment by deepak786** [comment]
@orestesgaolin Looking forward to your findings.

**Comment by parthsanghani525** [comment]
@orestesgaolin Getting same issue 

```
java.lang.IllegalStateException: ViewTreeLifecycleOwner not found from android.widget.FrameLayout{8c37a13 V.E...... ......ID 0,0-1080,2214 #7f0801b0 app:id/intercom_overlay_root}
 	at androidx.compose.ui.platform.WindowRecomposer_androidKt.createLifecycleAwareWindowRecomposer(WindowRecomposer.android.kt:349)
 	at androidx.compose.ui.platform.WindowRecomposer_androidKt.createLifecycleAwareWindowRecomposer$default(WindowRecomposer.android.kt:324)
 	at androidx.compose.ui.platform.WindowRecomposerFactory$Companion$LifecycleAware$1.createRecomposer(WindowRecomposer.android.kt:168)
 	at androidx.compose.ui.platform.WindowRecomposerPolicy.createAndInstallWindowRecomposer$ui_release(WindowRecomposer.android.kt:224)
 	at androidx.compose.ui.platform.WindowRecomposer_androidKt.getWindowRecomposer(WindowRecomposer.android.kt:299)
 	at androidx.compose.ui.platform.AbstractComposeView.resolveParentCompositionContext(ComposeView.android.kt:242)
 	at androidx.compose.ui.platform.AbstractComposeView.ensureCompositionCreated(ComposeView.android.kt:249)
 	at androidx.compose.ui.platform.AbstractComposeView.createComposition(ComposeView.android.kt:194)
 	at androidx.compose.ui.platform.ComposeView.setContent(ComposeView.android.kt:420)
 	at io.intercom.android.sdk.m5.notification.InAppNotificationCardKt.addTicketHeaderToCompose(InAppNotificationCard.kt:55)
 	at io.intercom.android.sdk.overlay.StackableSnippet.setViewData(StackableSnippet.java:101)
 	at io.intercom.android.sdk.overlay.StackableSnippet.display(StackableSnippet.java:49)
 	at io.intercom.android.sdk.overlay.InAppNotificationPresenter.addNewNotifications(InAppNotificationPresenter.java:184)
 	at io.intercom.android.sdk.overlay.InAppNotificationPresenter.displayNotificationsAfterAttach(InAppNotificationPresenter.java:90)
 	at io.intercom.android.sdk.overlay.InAppNotificationPresenter$1.run(InAppNotificationPresenter.java:79)
 	at io.intercom.android.sdk.utilities.ViewUtils$1.onGlobalLayout(ViewUtils.java:30)
 	at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1080)
 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4098)
 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2924)
 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10513)
 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
 	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
 	at android.view.Choreographer.doFrame(Choreographer.java:797)
 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
 	at android.os.Handler.handleCallback(Handler.java:938)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loopOnce(Looper.java:226)
 	at android.os.Looper.loop(Looper.java:313)
 	at android.app.ActivityThread.main(ActivityThread.java:8751)
 	at java.lang.reflect.Method.invoke(Native Method)
 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
 
```

**Comment by deepak786** [comment]
@parthsanghani525 Your exception is different.
You need to change your `MainActivity` on the Android side to extend from `FlutterFragmentActivity` instead of `FlutterActivity`. 
See https://github.com/v3rm0n/intercom_flutter/blob/master/intercom_flutter/example/android/app/src/main/kotlin/io/maido/intercomexample/MainActivity.kt

**Comment by devalp-pro** [comment]
Hi @deepak786 
Any updates from the intercom? or We got the solutions for this crash?

Thanks
Deval

**Comment by deepak786** [comment]
@devalp-pro The solution is to extend the `MainActivity` with `FlutterFragmentActivity` instead of `FlutterActivity`.
We already updated the docs https://pub.dev/packages/intercom_flutter#push-notifications-setup

![Screen Shot 2022-12-07 at 4 17 22 PM](https://user-images.githubusercontent.com/14223997/206159101-032565c2-819c-4fca-8a6b-bbca91363571.png)

**Comment by nialljawad96** [comment]
@deepak786 @orestesgaolin I've used the above solution re MainActivity extending FlutterFragmentActivity, but my users are still receiving exactly the same error. 

Has that solution above been tested to fix the issue?

```
`Fatal Exception: java.lang.IllegalStateException: ViewTreeLifecycleOwner not found from android.widget.FrameLayout{cb1448a V.E...... ......ID 0,0-2560,1498 #7f0a01ca app:id/intercom_overlay_root}
       at androidx.compose.ui.platform.WindowRecomposer_androidKt.createLifecycleAwareWindowRecomposer(WindowRecomposer_androidKt.java:162)
       at androidx.compose.ui.platform.WindowRecomposer_androidKt.createLifecycleAwareWindowRecomposer$default(WindowRecomposer_androidKt.java:11)
       at androidx.compose.ui.platform.WindowRecomposerFactory$Companion$LifecycleAware$1.createRecomposer(WindowRecomposerFactory.java:7)
       at androidx.compose.ui.platform.WindowRecomposerPolicy.createAndInstallWindowRecomposer$ui_release(WindowRecomposerPolicy.java:13)
       at androidx.compose.ui.platform.WindowRecomposer_androidKt.getWindowRecomposer(WindowRecomposer_androidKt.java:23)
       at androidx.compose.ui.platform.AbstractComposeView.resolveParentCompositionContext(AbstractComposeView.java:41)
       at androidx.compose.ui.platform.AbstractComposeView.ensureCompositionCreated(AbstractComposeView.java:8)
       at androidx.compose.ui.platform.AbstractComposeView.createComposition(AbstractComposeView.java:16)
       at androidx.compose.ui.platform.ComposeView.setContent(ComposeView.java:19)
       at io.intercom.android.sdk.m5.notification.InAppNotificationCardKt.addTicketHeaderToCompose(InAppNotificationCardKt.java:23)
       at io.intercom.android.sdk.overlay.ChatNotification.populateViewsWithData(ChatNotification.java:77)
       at io.intercom.android.sdk.overlay.ChatNotification.display(ChatNotification.java:66)
       at io.intercom.android.sdk.overlay.InAppNotificationPresenter.addNewNotifications(InAppNotificationPresenter.java:127)
       at io.intercom.android.sdk.overlay.InAppNotificationPresenter.displayNotificationsAfterAttach(InAppNotificationPresenter.java:39)
       at io.intercom.android.sdk.overlay.InAppNotificationPresenter$1.run(InAppNotificationPresenter.java:6)
       at io.intercom.android.sdk.utilities.ViewUtils$1.onGlobalLayout(ViewUtils.java:7)
       at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1084)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4203)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3017)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10699)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1301)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
       at android.view.Choreographer.doCallbacks(Choreographer.java:923)
       at android.view.Choreographer.doFrame(Choreographer.java:852)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8775)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)`
```

**Comment by nialljawad96** [comment]
@deepak786 @devalp-pro @parthsanghani525 any updates on this package crashing for Android? At the moment it isn't usable for Android, so a disclaimer needs to be put on the Package Notes.

**Comment by deepak786** [comment]
@nialljawad96 Your exception should be resolved with extending the MainActivity with FlutterFragmentActivity.
But if you can provide the sample reproducing this issue then it would be great.

**Comment by sjoulbak** [comment]
Hi @nialljawad96,

We're experiencing the same crash at our Android releases. We've asked the same question at Intercom: https://forum.intercom.com/s/question/0D55c00006kl0vpCAA/android-app-crash-with-iointercomandroidsdkm5notificationinappnotificationcardktaddticketheadertocompose Hopefully they can help us with the issue

**Comment by QPAYRE** [comment]
Got the same problem here and a part of my android users can't launch the app. Even if I use `FlutterFragmentActivity` instead of `FlutterActivity`.

**Comment by QPAYRE** [comment]
Ok after investigating during a whole day I figured out that you have to delete app data before re-launch it (Android only). I don't have error anymore and it's finally stable for my users.

**Comment by sjoulbak** [comment]
Cool @QPAYRE!

What do you mean with `you have to delete app data before re-launch it`? Is this something that every user has to do manually or is this something that can be achieved programmely?

**Comment by QPAYRE** [comment]
@sjoulbak ,

You have to inform your users to do it manually. At the moment it seems to be the only solution. Fortunately it has impacted only 17 users of mine..

And another information that can be interesting, it impacted especially Samsung users, I tested on Huawei, Motorola, OnePlus and worked well. There was no issue even using `FlutterActivity` in `MainActivity.kt`.

Now I don't have issue anymore reported by Crashlytics (using Firebase). I also implemented a force update so all my users have to install the new release.

**Comment by orestesgaolin** [comment]
I can confirm that the issue with Platform Views still occurs when using `FlutterFragmentActivity` (Flutter 3.7.6). Removing the app (cleaning the data) does not help in my case (Samsung S21)

**Comment by deepak786** [comment]
Users are confused with the exception. There are 2 exceptions.

<details>
<summary>Platform Channel Exception</summary>

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(error, java.lang.IllegalStateException: Trying to create a platform view of unregistered type: cameraView
	at io.flutter.plugin.platform.PlatformViewsController$1.createForPlatformViewLayer(PlatformViewsController.java:175)
	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:109)
	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:60)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
, null, null). Error thrown Zone error.
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:653)
       at MethodChannel._invokeMethod(platform_channel.dart:296)
       at ExpensiveAndroidViewController._sendCreateMessage(platform_views.dart:1023)
       at AndroidViewController.create(platform_views.dart:792)
```
</details>

<details>
<summary>Native Android Exception</summary>

```
Fatal Exception: java.lang.IllegalStateException: ViewTreeLifecycleOwner not found from android.widget.FrameLayout{cb1448a V.E...... ......ID 0,0-2560,1498 #7f0a01ca app:id/intercom_overlay_root}
       at androidx.compose.ui.platform.WindowRecomposer_androidKt.createLifecycleAwareWindowRecomposer(WindowRecomposer_androidKt.java:162)
       at androidx.compose.ui.platform.WindowRecomposer_androidKt.createLifecycleAwareWindowRecomposer$default(WindowRecomposer_androidKt.java:11)
       at androidx.compose.ui.platform.WindowRecomposerFactory$Companion$LifecycleAware$1.createRecomposer(WindowRecomposerFactory.java:7)
       at androidx.compose.ui.platform.WindowRecomposerPolicy.createAndInstallWindowRecomposer$ui_release(WindowRecomposerPolicy.java:13)
       at androidx.compose.ui.platform.WindowRecomposer_androidKt.getWindowRecomposer(WindowRecomposer_androidKt.java:23)
       at androidx.compose.ui.platform.AbstractComposeView.resolveParentCompositionContext(AbstractComposeView.java:41)
       at androidx.compose.ui.platform.AbstractComposeView.ensureCompositionCreated(AbstractComposeView.java:8)
       at androidx.compose.ui.platform.AbstractComposeView.createComposition(AbstractComposeView.java:16)
       at androidx.compose.ui.platform.ComposeView.setContent(ComposeView.java:19)
       at io.intercom.android.sdk.m5.notification.InAppNotificationCardKt.addTicketHeaderToCompose(InAppNotificationCardKt.java:23)
       at io.intercom.android.sdk.overlay.ChatNotification.populateViewsWithData(ChatNotification.java:77)
       at io.intercom.android.sdk.overlay.ChatNotification.display(ChatNotification.java:66)
       at io.intercom.android.sdk.overlay.InAppNotificationPresenter.addNewNotifications(InAppNotificationPresenter.java:127)
       at io.intercom.android.sdk.overlay.InAppNotificationPresenter.displayNotificationsAfterAttach(InAppNotificationPresenter.java:39)
       at io.intercom.android.sdk.overlay.InAppNotificationPresenter$1.run(InAppNotificationPresenter.java:6)
       at io.intercom.android.sdk.utilities.ViewUtils$1.onGlobalLayout(ViewUtils.java:7)
       at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1084)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4203)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3017)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10699)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1301)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
       at android.view.Choreographer.doCallbacks(Choreographer.java:923)
       at android.view.Choreographer.doFrame(Choreographer.java:852)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
       at android.os.Handler.handleCallback(Handler.java:942)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8775)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```
</details>

Intercom v14 has **Native Android Exception** which is solved by using the `FlutterFragmentActivity` instead of `FlutterActivity`.
But using the `FlutterFragmentActivity` gives another **Platform Channel Exception** if you are using the plugin that uses the Platform Views such as `Camera`.

This Issue is to investigate the **Platform channel exception**. 

_If you are facing the **Native Android Exception** then the solution is to extend your MainActivity with `FlutterFragmentActivity`._

There are other packages such as [local_auth](https://pub.dev/packages/local_auth#android-integration) which also asks to use the `FlutterFragmentActivity`.  And that local_auth package is used by lot of devs as per the popularity and likes. If using the `FlutterFragmentActivity` breaks another Flutter plugin that has Platform Views then it must be an issue with the local_auth package also. And I didn't find any such reference.

@orestesgaolin Can you try to reproduce the **Platform channel exception** using the local_auth and camera package (which shows Platform channel exception), but without the intercom_flutter package?

**Comment by orestesgaolin** [comment]
Interestingly I was able to use the newest version of Intercom **without** changing from `FlutterActivity` to `FlutterFragmentActivity`. My platform views still work fine.

On Android 13 both in-app messaging, as well as opening from push notification work fine.
On Android 9 it looks a little bit off with different navigation transition but still works fine and does not crash the app.

Could you verify if this is still necessary to use `FlutterFragmentActivity`?

**Comment by deepak786** [comment]
Intercom Android 14.0.5 has the following in the changelog. And the latest `intercom_flutter: 7.6.5` is using the SDK version 14.0.5. So might be that they resolved this issue of using the `FlutterFragmentActivity`. I will confirm with them.

![Screen Shot 2023-03-04 at 2 03 13 AM](https://user-images.githubusercontent.com/14223997/222823536-e8728f2d-20fc-4b3d-90d9-9a514ac4917c.png)

**Comment by deepak-agendaboa** [comment]
Intercom confirmed that there is no longer need to use the `FlutterFragmentActivity`. It is already resolved in 14.0.5 which is used by `intercom_flutter: 7.6.5`

```
Just a quick follow-up here Deepak, to let you know that the team confirmed there's no longer a requirement to use "FlutterFragmentActivity" 👍. 
```

**Comment by deepak786** [comment]
Intercom confirmed that there is no longer a need to use the `FlutterFragmentActivity`. It is already resolved in 14.0.5 which is used by `intercom_flutter: 7.6.5`

```
Just a quick follow-up here Deepak, to let you know that the team confirmed there's no longer a requirement to use "FlutterFragmentActivity" 👍. 
```
